spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: demo
server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰和下划线的转化,完成数据封装
